services:
  - type: web
    name: expense-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: expense-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: EMAIL_USER
        value: your-email@gmail.com
      - key: EMAIL_PASSWORD
        value: your-app-password
      - key: ENVIRONMENT
        value: production
      - key: USE_GUNICORN
        value: "true"
      - key: WORKERS
        value: "4"
    healthCheckPath: /health

databases:
  - name: expense-db
    databaseName: expense_system
    user: expense_user